### ISSUE TITLE
Unable to test when scss exports local variables

### ISSUE THREAD

**Issue by seekshiva** [atecarlos/webpack-babel-jest#6]
I have an SCSS file that looks like

``` scss
:local(.star-rating){
    color: #e0e5e8;

    &.active{
        color: #ff992f;
    }
}
:local(.custom-class){
    color: red;
}
```

in my jsx file I do

``` jsx
import styles from './StarRatings.scss'

class MyComponent extends Component {
  render() {
    return (
        <div className={styles['custom-class']}>
          <span className={styles['star-rating']} />
        </div>
    )
  }
}
```

due to replacing the require(*.scss) statement with '', my `import styles from './StarRatings.scss'` line fails with this error when I try to run tests:

```
  - SyntaxError: Unexpected token var
        at eval (native)
        at Object.eval (jsx/components/RatingStars/index.js:1:243)
```

Is there a way to not ignore the styles? This is breaking my tests.
